spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # --- User Service Paths ---
        - id: users_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**

        - id: genres_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/genres/**

        - id: skills_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/skills/**

        - id: interactions_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/interactions/**

        # --- Chat Service Paths ---
        - id: messages_route
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/messages/**

        - id: chats_route
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/chats/**

        # --- Project Service Paths ---
        - id: projects_route
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/projects/**

server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
